### ISSUE TITLE
PMO URIs incorrect syntax

### ISSUE THREAD

**Issue by cmungall** [hurwitzlab/planet-microbe-datapackages#21]
https://github.com/hurwitzlab/planet-microbe-datapackages/blob/master/Tara_Oceans/AHX/ontologies/campaign.tsv

some of these have the .owl in the URI, which I think is a mistake

btw, PMO doesn't resolve on OBO - is the OBO namespace correct?

**Comment by kaiiam** [comment]
Yes the IRIs with .owl resulted from a mistake while making them.

> PMO doesn't resolve on OBO

This is intentional it's an application ontology so I don't think it should be registered on OBO and confuse the domain space. 

That being said I'll need to fix to IRIs in: 

`alkalinity of water` http://purl.obolibrary.org/obo/pmo.owl/PMO_00000139 and `dissolved inorganic carbon` http://purl.obolibrary.org/obo/pmo.owl/PMO_00000142

**Comment by kaiiam** [comment]
This is now fixed in the ontology edit file. Update fixed for real.
